steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-gke-repo/node-gke-app:$SHORT_SHA', '.']

# Step 2: Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-gke-repo/node-gke-app:$SHORT_SHA']

# Step 3: Update Kubernetes manifest with new image tag
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i "s|us-central1-docker.pkg.dev/.*/node-gke-app:.*|us-central1-docker.pkg.dev/$PROJECT_ID/node-gke-repo/node-gke-app:$SHORT_SHA|" k8s/deployment.yaml

# Step 4: Deploy to GKE using kubectl
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=node-gke-cluster'

# List images to keep metadata of what was built
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/node-gke-repo/node-gke-app:$SHORT_SHA'

# ✅ Explicitly use the custom service account for all steps
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/cloudbuild-deployer@$PROJECT_ID.iam.gserviceaccount.com'
